name: Backend CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: node:20-bookworm
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: "admin"
          POSTGRES_PASSWORD: "admin"
          POSTGRES_DB: "test_fresh_market"
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install Dependencies
        working-directory: ./backend
        run: npm install
      - name: Run Vitest
        working-directory: ./backend
        run: npm t
        env:
          NODE_ENV: "test"
          FM_DB_USER: "admin"
          FM_DB_PASSWORD: "admin"
          FM_DB_NAME: "fresh_market"
          FM_DB_HOST: "postgres"
          FM_DB_PORT: "5432"
          FM_DB_CONNECTOR: "postgres"
